config/routes.rb
JetRails::Application.routes.draw do
  resources :flights
  match 'flights/date/:date' => 'flights#date'

  root :to => 'application#index'
  match '/zombies/ajax' => 'zombies#ajax'
  resources :zombies

end

app/models/flight.rb
class Flight < ActiveRecord::Base
  attr_accessible :arrive, :coach, :depart, :first_class, :flight_num, :routing

end

app/models/zombie.rb
class Zombie < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  def index
    render 'index.html.haml'
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  # GET /flights
  # GET /flights.json
  def date
    # Выдаем список полетов на дату
    #@flights = Flight.where('depart >= :depart AND depart <= :depart2',
    #                        {depart: '2013-01-04', depart2: '2013-01-25'}).order('depart ASC')
    #start_dt = params[:date] + ' 00:00:00'
    #end_dt = params[:date] + ' 23:59:59'
    #@flights = Flight.where('depart >= "2013-01-01 00:00:00" AND depart <= "2013-01-05 00:00:00"')
    start_dt = DateTime.parse(params[:date]).beginning_of_day
    end_dt = DateTime.parse(params[:date]).end_of_day
    @flights = Flight.where('depart >= :start AND depart <= :end',
                            {start: start_dt, end: end_dt}).order('depart ASC')

    if request.xhr?
      render partial: 'date.html.haml'
    end
    #respond_to do |format|
    #  format.html # index.html.erb
    #  format.xml { render text: 'Here I am' }
    #  format.json { render json: 'Here I am' }
    #end
  end

  def index
    @flights = Flight.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @flights }
    end
  end

  # GET /flights/1
  # GET /flights/1.json
  def show
    @flight = Flight.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @flight }
    end
  end

  # GET /flights/new
  # GET /flights/new.json
  def new
    @flight = Flight.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @flight }
    end
  end

  # GET /flights/1/edit
  def edit
    @flight = Flight.find(params[:id])
  end

  # POST /flights
  # POST /flights.json
  def create
    @flight = Flight.new(params[:flight])

    respond_to do |format|
      if @flight.save
        format.html { redirect_to @flight, notice: 'Flight was successfully created.' }
        format.json { render json: @flight, status: :created, location: @flight }
      else
        format.html { render action: "new" }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /flights/1
  # PUT /flights/1.json
  def update
    @flight = Flight.find(params[:id])

    respond_to do |format|
      if @flight.update_attributes(params[:flight])
        format.html { redirect_to @flight, notice: 'Flight was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flights/1
  # DELETE /flights/1.json
  def destroy
    @flight = Flight.find(params[:id])
    @flight.destroy

    respond_to do |format|
      format.html { redirect_to flights_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/project_controller.rb
class ProjectController < ApplicationController
end

app/controllers/zombies_controller.rb
class ZombiesController < ApplicationController
  # GET /zombies
  # GET /zombies.json
  def index
    @zombies = Zombie.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @zombies }
    end
  end

  # GET /zombies/1
  # GET /zombies/1.json
  def show
    @zombie = Zombie.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @zombie }
    end
  end

  # GET /zombies/new
  # GET /zombies/new.json
  def new
    @zombie = Zombie.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @zombie }
    end
  end

  # GET /zombies/1/edit
  def edit
    @zombie = Zombie.find(params[:id])
  end

  # POST /zombies
  # POST /zombies.json
  def create
    @zombie = Zombie.new(params[:zombie])

    respond_to do |format|
      if @zombie.save
        format.html { redirect_to @zombie, notice: 'Zombie was successfully created.' }
        format.json { render json: @zombie, status: :created, location: @zombie }
      else
        format.html { render action: "new" }
        format.json { render json: @zombie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /zombies/1
  # PUT /zombies/1.json
  def update
    @zombie = Zombie.find(params[:id])

    respond_to do |format|
      if @zombie.update_attributes(params[:zombie])
        format.html { redirect_to @zombie, notice: 'Zombie was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @zombie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zombies/1
  # DELETE /zombies/1.json
  def destroy
    @zombie = Zombie.find(params[:id])
    @zombie.destroy

    respond_to do |format|
      format.html { redirect_to zombies_url }
      format.json { head :no_content }
    end
  end

  def ajax
    @output = 'Ajax response! <b>Time:</b> ' + Time.now.to_s()
    respond_to do |format|
      format.json { render json: @output }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/zombies_helper.rb
module ZombiesHelper
end

app/views/application/index.html.haml
%p This is Haml template!
%p from Application/index.html.haml
%h1 Learn HTML5 and jQuery Air:

#wrapper
  #block
    %h3#tabs_header SELECT A FLIGHT
    %section#tabs
      %ul
        %li
          %a{href: "#2012-09-27", data: {flights: "6"}} Sep 27
        %li
          %a{href: "#2012-09-28", data: {flights: "5"}} Sep 28
        %li
          %a{href: "#2012-09-29", data: {flights: "5"}} Sep 29
        %li
          %a{href: "#2012-09-30", data: {flights: "7"}} Sep 30
        %li
          %a{href: "#2012-10-01", data: {flights: "4"}} Oct 01
        %li
          %a{href: "#2012-10-02", data: {flights: "3"}} Oct 02

    %div.cont#2012-09-27 Loading Sep 27
    %div.cont#2012-09-28 Loading Sep 28
    %div.cont#2012-09-29 Loading Sep 29
    %div.cont#2012-09-30 Loading Sep 30
    %div.cont#2012-10-01 Loading Oct 1
    %div.cont#2012-10-02 Loading Oct 2
    %div#error
      %h3 Whoops, unable to pull flights.
      %p
        Sorry about that,
        %a{href: '#'} Click Here to try again.
    %div#loading
      %h3 Just a minute while we pull up your flight

  %section#confirm
    %div.flight-review
      %table
        %tr
          %th Base Price:
          %td#price
        %tr
          %th Govt. Taxes:
          %td#fees
        %tr.total
          %th Trip Total:
          %td.total

app/views/flights/_date.html.haml
%table#flights
  %tr
    %th
      Depart
    %th
      Arrive
    %th
      Flight #
    %th
      Routing
    %th
      First Class
    %th
      Coach

  - @flights.each do |flight|
    %tr{class: cycle('odd', 'even')}
      %td
        = flight.depart.strftime("%H:%M")
      %td
        = flight.arrive.strftime("%H:%M")
      %td
        = flight.flight_num
      %td
        = flight.routing
      %td
        %a{href: '#', data: {class: 'first-class', flight: flight.flight_num}}
          = '$' + flight.first_class.to_s
      %td
        %a{href: '#', data: {class: 'first-class', flight: flight.flight_num}}
          = '$' + flight.coach.to_s

app/views/flights/_form.html.haml
= form_for @flight do |f|
  - if @flight.errors.any?
    #error_explanation
      %h2= "#{pluralize(@flight.errors.count, "error")} prohibited this flight from being saved:"
      %ul
        - @flight.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :depart
    = f.datetime_select :depart
  .field
    = f.label :arrive
    = f.datetime_select :arrive
  .field
    = f.label :flight_num
    = f.number_field :flight_num
  .field
    = f.label :routing
    = f.text_field :routing
  .field
    = f.label :first_class
    = f.text_field :first_class
  .field
    = f.label :coach
    = f.text_field :coach
  .actions
    = f.submit 'Save'

app/views/flights/date.html.haml
%table#flights
  %tr
    %th
      Depart
    %th
      Arrive
    %th
      Flight #
    %th
      Routing
    %th
      First Class
    %th
      Coach

  - @flights.each do |flight|
    %tr{class: cycle('odd', 'even')}
      %td
        = flight.depart.strftime("%H:%M")
      %td
        = flight.arrive.strftime("%H:%M")
      %td
        = flight.flight_num
      %td
        = flight.routing
      %td
        %a{href: '#'}
          = '$' + flight.first_class.to_s
      %td
        %a{href: '#'}
          = '$' + flight.coach.to_s

= link_to 'Back to Flights', flights_path

app/views/flights/edit.html.haml
%h1 Editing flight

= render 'form'

= link_to 'Show', @flight
\|
= link_to 'Back', flights_path

app/views/flights/index.html.haml
%h1 Listing flights

%table
  %tr
    %th Depart
    %th Arrive
    %th Flight num
    %th Routing
    %th First class
    %th Coach
    %th
    %th
    %th

  - @flights.each do |flight|
    %tr
      %td= flight.depart
      %td= flight.arrive
      %td= flight.flight_num
      %td= flight.routing
      %td= flight.first_class
      %td= flight.coach
      %td= link_to 'Show', flight
      %td= link_to 'Edit', edit_flight_path(flight)
      %td= link_to 'Destroy', flight, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Flight', new_flight_path

app/views/flights/new.html.haml
%h1 New flight

= render 'form'

= link_to 'Back', flights_path

app/views/flights/show.html.haml
%p#notice= notice

%p
  %b Depart:
  = @flight.depart
%p
  %b Arrive:
  = @flight.arrive
%p
  %b Flight num:
  = @flight.flight_num
%p
  %b Routing:
  = @flight.routing
%p
  %b First class:
  = @flight.first_class
%p
  %b Coach:
  = @flight.coach

= link_to 'Edit', edit_flight_path(@flight)
\|
= link_to 'Back', flights_path

app/views/layouts/application.html.haml
!!! 5
= link_to 'Home', root_path, class: 'to-root'
%html
  %head
    %title JetRails
    = stylesheet_link_tag    "application", :media => "all"
    = stylesheet_link_tag    'http://fonts.googleapis.com/css?family=Maiden Orange|Rye'
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body

    = yield

    = link_to 'Back to Flights', flights_path, class: 'to-flights'
    %div#output
      Super!

app/views/zombies/_form.html.erb
<%= form_for(@zombie) do |f| %>
  <% if @zombie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@zombie.errors.count, "error") %> prohibited this zombie from being saved:</h2>

      <ul>
      <% @zombie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/zombies/edit.html.erb
<h1>Editing zombie</h1>

<%= render 'form' %>

<%= link_to 'Show', @zombie %> |
<%= link_to 'Back', zombies_path %>

app/views/zombies/index.html.erb
<h1>Listing zombies</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @zombies.each do |zombie| %>
  <tr>
    <td><%= zombie.name %></td>
    <td><%= link_to 'Show', zombie %></td>
    <td><%= link_to 'Edit', edit_zombie_path(zombie) %></td>
    <td><%= link_to 'Destroy', zombie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Zombie', new_zombie_path %>

app/views/zombies/new.html.erb
<h1>New zombie</h1>

<%= render 'form' %>

<%= link_to 'Back', zombies_path %>

app/views/zombies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @zombie.name %>
</p>


<%= link_to 'Edit', edit_zombie_path(@zombie) %> |
<%= link_to 'Back', zombies_path %>